version: "4"
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app_network

  redis:
    image: redis:8.0
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app_network

volumes:
  mysql_data:
  redis_data:

networks:
  app_network:
